-- ================================================================
-- PRONOGOL - Migración 001: Esquema Inicial
-- ================================================================
-- Fecha: 2026-06-29
-- Descripción: Tablas base del sistema de pronósticos
-- ================================================================

-- 1. EXTENSIONES
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

-- ================================================================
-- 2. TABLAS DEL SISTEMA
-- ================================================================

-- 2.1 Ligas
create table leagues (
  id            bigint generated by default as identity primary key,
  name          text not null,
  country       text not null,
  season_id     int,
  logo_url      text,
  active        boolean default true,
  created_at    timestamptz default now()
);
comment on table leagues is 'Ligas de fútbol disponibles en la plataforma';

-- 2.2 Equipos
create table teams (
  id            bigint generated by default as identity primary key,
  league_id     bigint references leagues(id) on delete cascade,
  name          text not null,
  short_name    text,
  logo_url      text,
  created_at    timestamptz default now()
);
comment on table teams is 'Equipos de fútbol por liga';

-- 2.3 Partidos
create table matches (
  id            bigint generated by default as identity primary key,
  league_id     bigint references leagues(id) on delete cascade,
  home_team_id  bigint references teams(id) on delete cascade,
  away_team_id  bigint references teams(id) on delete cascade,
  match_date_utc timestamptz not null,
  status        text default 'scheduled' check (status in ('scheduled','live','finished','postponed','cancelled')),
  home_score    int,
  away_score    int,
  foosty_id     text unique,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);
create index idx_matches_date on matches(match_date_utc);
create index idx_matches_league on matches(league_id);
create index idx_matches_status on matches(status);
comment on table matches is 'Partidos con fecha UTC y estado';

-- 2.4 Estadísticas del partido
create table match_stats (
  id              bigint generated by default as identity primary key,
  match_id        bigint references matches(id) on delete cascade unique,
  possession_home decimal(5,1),
  possession_away decimal(5,1),
  shots_home      int,
  shots_away      int,
  shots_ontarget_home int,
  shots_ontarget_away int,
  corners_home    int,
  corners_away    int,
  cards_yellow_home int,
  cards_yellow_away int,
  cards_red_home  int,
  cards_red_away  int,
  xg_home         decimal(4,2),
  xg_away         decimal(4,2),
  fouls_home      int,
  fouls_away      int,
  updated_at      timestamptz default now(),
  created_at      timestamptz default now()
);
comment on table match_stats is 'Estadísticas detalladas del partido';

-- 2.5 Pronósticos (el core del negocio)
create table predictions (
  id              uuid default gen_random_uuid() primary key,
  match_id        bigint not null references matches(id) on delete cascade,
  market          text not null check (market in ('1x2','double_chance','over_under','btts','handicap','corners','correct_score')),
  predicted_value text not null,
  probability     decimal(5,2) not null,
  factors_json    jsonb not null default '{}',
  model_version   text not null default '1.0',
  created_at      timestamptz not null default now()
);
create index idx_predictions_match on predictions(match_id);
create index idx_predictions_market on predictions(market);
create index idx_predictions_created on predictions(created_at);
comment on table predictions is 'Pronósticos generados por el motor IA — timestamp INMUTABLE para auditoría';

-- 2.6 Resultados de pronósticos (historial auditable)
create table prediction_results (
  id              uuid default gen_random_uuid() primary key,
  prediction_id   uuid not null references predictions(id) on delete cascade unique,
  actual_result   text not null,
  correct         boolean not null,
  evaluated_at    timestamptz not null default now()
);
create index idx_prediction_results_correct on prediction_results(correct);
comment on table prediction_results is 'Resultado real de cada pronóstico — HISTÓRICO PÚBLICO';

-- 2.7 Perfiles de usuario (vinculado a Supabase Auth)
create table profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text not null,
  display_name    text,
  avatar_url      text,
  role            text default 'user' check (role in ('user','admin')),
  stripe_customer_id text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
comment on table profiles is 'Perfiles de usuario vinculados a Supabase Auth';

-- 2.8 Suscripciones
create type subscription_plan as enum ('free', 'premium_monthly', 'premium_annual');
create type subscription_status as enum ('active', 'canceled', 'past_due', 'trialing', 'incomplete', 'incomplete_expired');

create table subscriptions (
  id              uuid default gen_random_uuid() primary key,
  user_id         uuid not null references profiles(id) on delete cascade,
  plan            subscription_plan not null default 'free',
  status          subscription_status not null default 'trialing',
  stripe_subscription_id text,
  trial_ends_at   timestamptz,
  current_period_start timestamptz,
  current_period_end   timestamptz,
  canceled_at     timestamptz,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index idx_subscriptions_user on subscriptions(user_id);
create index idx_subscriptions_status on subscriptions(status);
comment on table subscriptions is 'Suscripciones vinculadas a Stripe';

-- 2.9 Pagos
create table payments (
  id                uuid default gen_random_uuid() primary key,
  user_id           uuid not null references profiles(id) on delete cascade,
  subscription_id   uuid references subscriptions(id) on delete set null,
  stripe_payment_id text,
  amount            int not null, -- en centavos
  currency          text default 'usd',
  status            text check (status in ('succeeded','failed','pending','refunded')),
  created_at        timestamptz default now()
);
create index idx_payments_user on payments(user_id);
comment on table payments is 'Historial de pagos';

-- 2.10 Favoritos del usuario
create table user_favorites (
  id        uuid default gen_random_uuid() primary key,
  user_id   uuid not null references profiles(id) on delete cascade,
  team_id   bigint references teams(id) on delete cascade,
  league_id bigint references leagues(id) on delete cascade,
  created_at timestamptz default now(),
  constraint chk_at_least_one_favorite check (team_id is not null or league_id is not null)
);
comment on table user_favorites is 'Equipos y ligas favoritas del usuario';

-- 2.11 Logs de auditoría
create table audit_logs (
  id          uuid default gen_random_uuid() primary key,
  user_id     uuid references profiles(id) on delete set null,
  action      text not null,
  ip_address  inet,
  user_agent  text,
  metadata    jsonb default '{}',
  created_at  timestamptz default now()
);
create index idx_audit_logs_user on audit_logs(user_id);
create index idx_audit_logs_action on audit_logs(action);
create index idx_audit_logs_created on audit_logs(created_at);
comment on table audit_logs is 'Registro de acciones sensibles para seguridad';

-- 2.12 Control de sincronización Foosty
create table sync_log (
  id            bigint generated by default as identity primary key,
  sync_type     text not null check (sync_type in ('fixtures','results','stats','leagues','teams')),
  started_at    timestamptz default now(),
  finished_at   timestamptz,
  status        text default 'running' check (status in ('running','completed','failed')),
  records_count int,
  error_message text,
  created_at    timestamptz default now()
);
comment on table sync_log is 'Registro de cada sincronización con Foosty';

-- ================================================================
-- 3. FUNCIÓN PARA ACTUALIZAR updated_at AUTOMÁTICAMENTE
-- ================================================================

create or replace function trigger_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Aplicar a todas las tablas con updated_at
create trigger set_updated_at before update on matches
  for each row execute function trigger_set_updated_at();
create trigger set_updated_at before update on match_stats
  for each row execute function trigger_set_updated_at();
create trigger set_updated_at before update on profiles
  for each row execute function trigger_set_updated_at();
create trigger set_updated_at before update on subscriptions
  for each row execute function trigger_set_updated_at();

-- ================================================================
-- 4. ROW LEVEL SECURITY - POLÍTICAS POR TABLA
-- ================================================================

-- Activar RLS en TODAS las tablas
alter table leagues enable row level security;
alter table teams enable row level security;
alter table matches enable row level security;
alter table match_stats enable row level security;
alter table predictions enable row level security;
alter table prediction_results enable row level security;
alter table profiles enable row level security;
alter table subscriptions enable row level security;
alter table payments enable row level security;
alter table user_favorites enable row level security;
alter table audit_logs enable row level security;
alter table sync_log enable row level security;

-- 4.1 Tablas públicas (lectura para anónimos)
create policy "Leagues son públicas" on leagues for select using (true);
create policy "Teams son públicos" on teams for select using (true);
create policy "Matches son públicos" on matches for select using (true);
create policy "Match_stats son públicos" on match_stats for select using (true);
create policy "Predictions públicas" on predictions for select using (true);
create policy "Prediction_results públicos" on prediction_results for select using (true);

-- 4.2 Perfiles: cada usuario solo ve/edita su perfil
create policy "Usuarios ven su perfil" on profiles
  for select using (auth.uid() = id);
create policy "Usuarios editan su perfil" on profiles
  for update using (auth.uid() = id);
-- El insert lo hace Supabase Auth automáticamente

-- 4.3 Suscripciones: cada usuario ve las suyas
create policy "Usuarios ven sus suscripciones" on subscriptions
  for select using (auth.uid() = user_id);

-- 4.4 Pagos: cada usuario ve los suyos
create policy "Usuarios ven sus pagos" on payments
  for select using (auth.uid() = user_id);

-- 4.5 Favoritos: CRUD completo solo para el dueño
create policy "Usuarios ven sus favoritos" on user_favorites
  for select using (auth.uid() = user_id);
create policy "Usuarios crean sus favoritos" on user_favorites
  for insert with check (auth.uid() = user_id);
create policy "Usuarios eliminan sus favoritos" on user_favorites
  for delete using (auth.uid() = user_id);

-- 4.6 Audit logs: nadie los lee excepto admin via service_role
create policy "Audit logs solo service_role" on audit_logs
  for all using (false);

-- 4.7 Sync log: solo service_role
create policy "Sync_log solo service_role" on sync_log
  for all using (false);

-- ================================================================
-- 5. FUNCIÓN PARA CREAR PERFIL AUTOMÁTICAMENTE AL REGISTRARSE
-- ================================================================

create or replace function handle_new_user()
returns trigger as $$
begin
  insert into profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  );
  -- Crear suscripción free automática
  insert into subscriptions (user_id, plan, status, trial_ends_at, current_period_start, current_period_end)
  values (
    new.id,
    'free',
    'active',
    null,
    now(),
    '2099-12-31'::timestamptz
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger que se ejecuta cuando se crea un usuario en auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ================================================================
-- 6. DATOS INICIALES (para desarrollo)
-- ================================================================

-- Nota: Los datos reales de ligas se sincronizan desde Foosty vía n8n
-- Estos son solo para desarrollo local
insert into leagues (name, country, season_id, active) values
  ('Mundial 2026', 'Internacional', 16494, true),
  ('Copa Chile', 'Chile', 14121, true),
  ('Veikkausliiga', 'Finlandia', 14089, true)
on conflict do nothing;

-- ================================================================
-- FIN DE MIGRACIÓN 001
-- ================================================================
